name: Perform Mixeway Scan

on: push

jobs:
  mixeway-scan:
    name: Mixeway Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Prepare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=branch::$(echo $GITHUB_REF | cut -d/ -f3)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Prepare Mixeway docker image
        run: docker pull mixeway/scanner:latest

      - name: Run Scan
        run: |
          docker run -e OSS_USERNAME=iga.miron@gmail.com \
          -e OSS_KEY=sonatype_pat_6-ry1bXi4UeFpH1RA_Ph1OVHQMzH-_7emgP2riS55Ch7xE9d \
          -e MIXEWAY_URL=https://flow.mixeway.io \
          -e MIXEWAY_KEY=acd2bf88-7e6c-4ecf-bb5a-9b8dbc506a83 \
          -e MIXEWAY_PROJECT_ID=18 \
          -e MODE=STANDALONE \
          -e MIXEWAY_PROJECT_NAME=https://github.com/igamiron/_lab_secure_app.git \
          -e COMMIT_ID=${{ steps.vars.outputs.sha_short }} \
          -e BRANCH=${{ steps.vars.outputs.branch }} \
          -v ${{ github.workspace }}:/opt/sources \
          mixeway/scanner:latest
